config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root "pages#index"
  resources :categories
  resources :subcategories
  resources :products

  resources :users, only: %i[show], param: :id do
    resource :cart, controller: 'cart', only: %i[show]
  end

  post 'cart/add'
  post 'cart/remove'
  get 'users/:user_id/products'=> 'products#user_products', as: :user_products

  resources :orders, only: %i[destroy] do
    collection do
      post :checked
    end
  end

end

app/views/navigator/_menu.html.erb
<%= provide :menu do %>
  <%= link_to "Home", root_path, class:"text-gray-600 hover:text-gray-800" %>
  <%= link_to "Catalogue", categories_path, class:"text-gray-600 hover:text-gray-800" %>
  <a class="text-gray-600 hover:text-gray-800" href="#">About</a>
<% end %>

app/views/navigator/_navbar.html.erb
<% menu_at %>
<%= provide :navigation do %>
  <div class="bg-gray-200 text-gray-800 w-full top-0 z-10 px-6">
    <div class="h-20 py-4 container mx-auto flex items-center justify-center">
      <!-- Begin Menu -->
      <div x-data="{ open: false }" class="z-10 flex-1">
        <div :class="{ 'flex' : open, 'hidden' : open === false }" class="fixed md:relative top-0 left-0 w-full md:w-auto h-screen md:h-auto md:flex flex-col md:flex-row items-center justify-center md:justify-start z-40 bg-gray-200 md:bg-transparent leading-loose font-sans uppercase text-gray-800 text-base md:text-xs tracking-wider gap-8 hidden">
          <%= yield :menu %>
        </div>
        <button @click="open = true" type="button" :class="{ 'hidden' : open, 'block' : !open }" class="block md:hidden text-4xl font-thin"> ＝ </button>
        <button @click="open = false" type="button" :class="{ 'block' : open, 'hidden' : !open }" class="md:hidden absolute top-0 left-0 leading-none p-8 text-xl z-50 hidden"> ╳ </button>
      </div>
      <!-- End Menu -->
      <div x-data="{ dropOpen: false}" class="relative py-1">
        <div>
          <button @click="dropOpen = !dropOpen" type="button" class="flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
            <span class="sr-only">Open user menu</span>
            <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </button>
        </div>
        <div x-show="dropOpen" @click.away="dropOpen = false" class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none px-2">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, data:{"turbo-method": :delete}, class:"flex-1 flex items-center justify-end text-xs uppercase tracking-wider gap-4" %>
            <%= link_to "Cart", user_cart_path(current_user), class:"flex-1 flex items-center justify-end text-xs uppercase tracking-wider gap-4" %>
            <%= link_to current_user.name, current_user, class:"flex-1 flex items-center justify-end text-xs uppercase tracking-wider gap-4" %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class:"flex-1 flex items-center justify-end text-xs uppercase tracking-wider gap-4" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>