config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root "pages#index"
  resources :categories
  resources :subcategories
  resources :products

  resources :users, only: %i[show], param: :id do
    resource :cart, controller: 'cart', only: %i[show]
  end

  post 'cart/add'
  post 'cart/remove'
  get 'users/:user_id/products'=> 'products#user_products', as: :user_products

  resources :orders, only: %i[destroy] do
    collection do
      post :checked
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories
  has_many :products, through: :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(created_at: :desc)
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def create
    @category = Category.create category_params
    if @category.save
      flash[:success] = "Object successfully created"
      redirect_to @category
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def update
    @category = Category.find_by(id: params[:id])
    if @category.update category_params
      flash[:success] = "Object successfully updated"
      redirect_to @category
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end
end

app/views/categories/_category.html.erb
<%= turbo_frame_tag category do %>
<%= category.title %>
</br>
<p>______________________________</p>
<% @category.subcategories.each do |subcategory| %>
  <%= link_to subcategory.title, subcategory_path(subcategory), data: { turbo: false } %>
<% end %>
<p>______________________________</p>
</br>
<%= render @category.products %>
<% end %>

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </br>
  <%= f.submit "Save" %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'categories/form' %>

app/views/categories/index.html.erb
<% navigation_at %>
<div class="p-20 bg-orange-200">
  <h3 class="text-orange-400 font-bold mb-4">3. Horizontal &amp; Responsive Card</h3>
  <div class="bg-white rounded-lg shadow-2xl md:flex">
    <img src="https://images.unsplash.com/photo-1593642532744-d377ab507dc8" alt="Laptop on Desk" class="md:w-1/3 rounded-t-lg md:rounded-l-lg md:rounded-t-none" />
    <div class="p-6">
      <h2 class="font-bold text-xl md:text-3xl mb-2 text-orange-700">Horizontal Card</h2>
      <p class="text-orange-700">
  <% @categories.each do |category| %>
    <%= link_to category.title, category_path(category) %>
    </br>
  <% end %>
      </p>
    </div>

  </div>
</div>

app/views/categories/new.html.erb
<%= render "categories/form" %>

app/views/categories/show.html.erb
<% navigation_at %>
<%= render @category %>