config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root "pages#index"
  resources :categories
  resources :subcategories
  resources :products

  resources :users, only: %i[show], param: :id do
    resource :cart, controller: 'cart', only: %i[show]
  end

  post 'cart/add'
  post 'cart/remove'
  get 'users/:user_id/products'=> 'products#user_products', as: :user_products

  resources :orders, only: %i[destroy] do
    collection do
      post :checked
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  belongs_to :subcategory
  has_many :orders
  has_many :reviews

  validate :content_validation

  after_save :touch_object

  private

  def content_validation
    errors.add( :base, "Field cannot be blank") if title.blank? || body.blank? || price.blank? || quantity.blank?
  end

  def touch_object
    user.touch
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(created_at: :desc)
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def user_products
    @user = current_user
    if @user.id == params[:user_id].to_i
      @products = Product.where(user_id: params[:user_id])
    else
      not_found
    end
  end

  def new
    @product = Product.new
    @categories = Category.order(created_at: :desc)
    @subcategories = Subcategory.order(created_at: :desc)
  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  def create
    @user = current_user
    if @user.status == "seller"
      @product = @user.products.create product_params
      if @product.save
        flash[:success] = "Object successfully created"
        redirect_to @product
      else
        flash[:error] = "Something went wrong"
        render 'new'
      end
    else
      flash[:error] = "Need to create seller account"
    end
  end

  def update
    @product = Product.find_by(id: params[:id])
    if @product.update product_params
      flash[:success] = "Object successfully updated"
      redirect_to @product
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :body, :quantity, :price, :subcategory_id, :user_id)
  end
end

app/views/products/_form.html.erb
<%= form_with model: @product do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </br>
  <%= f.label :body %>
  <%= f.text_field :body %>
  </br>
  <%= f.label :price %>
  <%= f.number_field :price %>
  </br>
  <%= f.label :quantity %>
  <%= f.number_field :quantity %>
  </br>
  <%= f.grouped_collection_select :subcategory_id, @categories, :subcategories, :title, :id, :title %>
  </br>
  <%= f.submit "SAVE" %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product.title, product_path(product), data:{turbo: false} %>
</br>
<%= product.price %>
</br>
<p>________________</p>

<p>________________</p>

app/views/products/edit.html.erb
<%= render 'products/form' %>

app/views/products/index.html.erb
<%= render @products %>

app/views/products/new.html.erb
<%= render 'products/form' %>

app/views/products/show.html.erb
<% navigation_at %>
<div class="antialiased">
  <div class="bg-indigo-700 text-indigo-200 md:text-center py-2 px-4">
    Inspired from Dribbble Shot by <a href="https://dribbble.com/shots/14127375-Product-Page" class="font-bold underline hover:text-indigo-100">Vishnu Prasad</a>.
    See his works on <a href="https://dribbble.com/vlockn" class="font-bold underline hover:text-indigo-100">Dribbble</a>.
  </div>

  <div class="bg-white shadow-sm sticky top-0">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-1 md:py-4">
      <div class="flex items-center justify-between md:justify-start">
        <!-- Menu Trigger -->
        <button type="button" class="md:hidden w-10 h-10 rounded-lg -ml-2 flex justify-center items-center">
          <svg class="text-gray-500 w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
        <!-- ./ Menu Trigger -->

        <a href="#" class="font-bold text-gray-700 text-2xl">Shop.</a>

        <div class="hidden md:flex space-x-3 flex-1 lg:ml-8">
          <a href="#" class="px-2 py-2 hover:bg-gray-100 rounded-lg text-gray-400 hover:text-gray-600">Electronics</a>
          <a href="#" class="px-2 py-2 hover:bg-gray-100 rounded-lg text-gray-400 hover:text-gray-600">Fashion</a>
          <a href="#" class="px-2 py-2 hover:bg-gray-100 rounded-lg text-gray-400 hover:text-gray-600">Tools</a>
          <a href="#" class="px-2 py-2 hover:bg-gray-100 rounded-lg text-gray-400 hover:text-gray-600">Books</a>
          <a href="#" class="px-2 py-2 hover:bg-gray-100 rounded-lg text-gray-400 hover:text-gray-600">More</a>
        </div>

        <div class="flex items-center space-x-4">
          <div class="relative hidden md:block">
            <input type="search" class="pl-10 pr-2 h-10 py-1 rounded-lg border border-gray-200 focus:border-gray-300 focus:outline-none focus:shadow-inner leading-none" placeholder="Search">
            <svg class="h-6 w-6 text-gray-300 ml-2 mt-2 stroke-current absolute top-0 left-0" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </div>

          <a href="#" class="flex h-10 items-center px-2 rounded-lg border border-gray-200 hover:border-gray-300 focus:outline-none hover:shadow-inner">
            <svg class="h-6 w-6 leading-none text-gray-300 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
            </svg>
            <span class="pl-1 text-gray-500 text-md">0</span>
          </a>

          <button type="button" class="hidden md:block w-10 h-10 rounded-lg bg-gray-100 border border-gray-200 flex justify-center items-center">
            <img src="https://avatars.dicebear.com/api/bottts/2.svg" alt="bottts" width="28" height="28" class="rounded-lg mx-auto">
          </button>
        </div>
      </div>

      <!-- Search Mobile -->
      <div class="relative md:hidden">
        <input type="search" class="mt-1 w-full pl-10 pr-2 h-10 py-1 rounded-lg border border-gray-200 focus:border-gray-300 focus:outline-none focus:shadow-inner leading-none" placeholder="Search">

        <svg class="h-6 w-6 text-gray-300 ml-2 mt-3 stroke-current absolute top-0 left-0" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
      </div>
      <!-- ./ Search Mobile -->

    </div>
  </div>

  <div class="py-6">
    <!-- Breadcrumbs -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center space-x-2 text-gray-400 text-sm">
        <%= link_to @product.subcategory.category.title, @product.subcategory.category, class:"hover:underline hover:text-gray-600" %>
        <span>
        <svg class="h-5 w-5 leading-none text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </span>
        <%= link_to @product.subcategory.title, @product.subcategory, class:"hover:underline hover:text-gray-600" %>
        <span>
        <svg class="h-5 w-5 leading-none text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </span>
        <span><%= @product.title.truncate(10) %></span>
      </div>
    </div>
    <!-- ./ Breadcrumbs -->

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6">
      <div class="flex flex-col md:flex-row -mx-4">
        <div class="md:flex-1 px-4">
          <div x-data="{ image: 1 }" x-cloak>
            <div class="h-64 md:h-80 rounded-lg bg-gray-100 mb-4">
              <div x-show="image === 1" class="h-64 md:h-80 rounded-lg bg-gray-100 mb-4 flex items-center justify-center">
                <span class="text-5xl">1</span>
              </div>

              <div x-show="image === 2" class="h-64 md:h-80 rounded-lg bg-gray-100 mb-4 flex items-center justify-center">
                <span class="text-5xl">2</span>
              </div>

              <div x-show="image === 3" class="h-64 md:h-80 rounded-lg bg-gray-100 mb-4 flex items-center justify-center">
                <span class="text-5xl">3</span>
              </div>

              <div x-show="image === 4" class="h-64 md:h-80 rounded-lg bg-gray-100 mb-4 flex items-center justify-center">
                <span class="text-5xl">4</span>
              </div>
            </div>

            <div class="flex -mx-2 mb-4">
              <template x-for="i in 4">
                <div class="flex-1 px-2">
                  <button x-on:click="image = i" :class="{ 'ring-2 ring-indigo-300 ring-inset': image === i }" class="focus:outline-none w-full rounded-lg h-24 md:h-32 bg-gray-100 flex items-center justify-center">
                    <span x-text="i" class="text-2xl"></span>
                  </button>
                </div>
              </template>
            </div>
          </div>
        </div>
        <div class="md:flex-1 px-4">
          <h2 class="mb-2 leading-tight tracking-tight font-bold text-gray-800 text-2xl md:text-3xl"><%= @product.title %></h2>
          <p class="text-gray-500 text-sm">By <a href="#" class="text-indigo-600 hover:underline">ABC Company</a></p>

          <div class="flex items-center space-x-4 my-4">
            <div>
              <div class="rounded-lg bg-gray-100 flex py-2 px-3">
                <span class="text-indigo-400 mr-1 mt-1">$</span>
                <span class="font-bold text-indigo-600 text-3xl"><%= @product.price %></span>
              </div>
            </div>
            <div class="flex-1">
              <p class="text-green-500 text-xl font-semibold">Save 12%</p>
              <p class="text-gray-400 text-sm">Inclusive of all Taxes.</p>
            </div>
          </div>

          <p class="text-gray-500"><%= @product.body %></p>

          <div class="flex py-4 space-x-4">
            <div class="relative">
              <%= form_with(url: cart_add_path) do |f| %>
                <%= f.hidden_field :id, value: @product.id %>
                <%= f.select :quantity, options_for_select((1..if @product.quantity < 10 then @product.quantity else 10 end).step(1)), {}, class:"cursor-pointer appearance-none rounded-xl border border-gray-200 pl-4 pr-8 h-14 flex items-end pb-1" %>
              <svg class="w-5 h-5 text-gray-400 absolute right-0 bottom-0 mb-[1.15rem] mr-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 9l4-4 4 4m0 6l-4 4-4-4" />
              </svg>
            </div>
                <%= f.submit "Add To Cart", class:"h-14 px-6 py-2 font-semibold rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/user_products.html.erb
<%= render @products %>